### ISSUE TITLE
Nameof

### ISSUE THREAD

**Issue by abergquist** [dotnet/csharpstandard#1073]
### Type of issue

Typo

### Description

Since "nameof" is the proper capitalization, I recommend that all occurrences of "Nameof" be replaced with "nameof".

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#12822-nameof-expressions

### Content source URL

https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md

**Comment by RexJaeschke** [comment]
The issue here is the name of the whole section, "12.8.22 Nameof expressions." I think this is a reasonable request, and I see two solutions:

1. Trivial solution: Change "Nameof expressions" to "nameof expressions." As links to sections use all-lowercase anyway, this won't break those.
2. A bit more work: For operators `new`, `sizeof`, and `typeof`, we've named those sections "The new operator," "The sizeof operator," and "The typeof operator." Doing that for `nameof` too would be consistent, but would require the links in README.md and variables.md to be changed. (Although grammar.md also includes a link to that section, I think that file is generated automatically.)

**Comment by BillWagner** [comment]
For 2, the tool that updates the links and the TOC should pick it up automatically, and update all links.

Let's do it.

**Comment by RexJaeschke** [comment]
@BillWagner I'll create a PR for this. I've removed the "meeting:discuss" label as this is an editorial nit that does not require TG2 attention.

**Comment by BillWagner** [comment]
Fixed in #1075
