### ISSUE TITLE
Unicode escape sequence in identifiers

### ISSUE THREAD

**Issue by logeshkumars0604** [dotnet/csharpstandard#1107]
### Type of issue

Typo

### Description

In the production fragment,

``` ANTLR
fragment Underscore_Character
    : '_'           // underscore
    | '\\u005' [fF] // Unicode_Escape_Sequence for underscore
    ;
```

shouldn't we include `'\U000005' [fF]` as well?

Source: [C# > Language Reference> Language Specification > Lexical Structure > Identifiers](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#643-identifiers)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure

### Content source URL

https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/lexical-structure.md

**Comment by RexJaeschke** [comment]
As the author of this grammar rule when we moved to ANTLR notation, I just took a look at this, and I agree with @logeshkumars0604. In the second case, we're *not* looking for a single character with the Unicode value of an underscore; instead, we're looking for a sequence of 6 (or 10) source characters than represent the underscore as a short- or long-form Unicode character, in which case, we need to support both prefix spellings. The corrected version is, as follows: 

```ANTLR
fragment Underscore_Character
    : '_'           // underscore
    | '\\u005' [fF] // Unicode_Escape_Sequence for underscore
    | '\\U0000005' [fF] // Unicode_Escape_Sequence for underscore
    ;
```

which is slightly different than what was suggested, as C# requires `\U` to be followed by *exactly* 8 hex digits.

This got me thinking about the other places we allow underscores as input.
1. As digit separators in dec/hex/bin literals. There, we don't allow the Unicode equivalents; we simply use `'_'` in the grammar rules (rather than the more permissive `Underscore_Character`). (This is reflected by the VS compiler.)
2. As a discard: This is *never* described in a grammar rule, only prose. And we don't allow the Unicode equivalents. (This is reflected by the VS compiler.)

**Comment by jskeet** [comment]
We agree with @RexJaeschke's proposal; he will create a PR which we can merge without a further meeting.
