### ISSUE TITLE
Nested class within a static class - static or non-static by implicit?

### ISSUE THREAD

**Issue by logeshkumars0604** [dotnet/csharpstandard#1189]
### Type of issue

Other (describe below)

### Description

> The members of a static class are not automatically static, and the member declarations shall explicitly include a `static` modifier (except for constants and nested types). When a class is nested within a static outer class, the nested class is not a static class unless it explicitly includes a `static` modifier.

Referring to the above text described [here](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#152241-general), the question is, if a class declared inside a static class is static by implicit or not?

A part of the text states that member declarations inside a static class are **not automatically static _except for_** constants and **nested types**.

A part also states that when a class is nested within a static class, the nested class is **not automatically static unless it explicitly includes a `static` modifier**.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes

### Content source URL

https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/classes.md

**Comment by KalleOlaviNiemitalo** [comment]
```csharp
public class A {
    public class B {}
    void M() {
        //// this.B b1; // invalid
        A.B b2; // OK
        B b3; // OK
    }
}

public static class C {
    public class D {}
}

public class E {
    public static class F {}
}
```

According to the specification:

* A.B is a **static member** of A, but A.B is not a **static class**.
* C.D is a **static member** of C, but C.D is not a **static class**.
* E.F is a **static member** of E, and E.F is a **static class**.

This looks consistent to me, even though the terminology may be a little surprising.

§15.2.2.4.1 *General* (in *Static classes*) says:

> A static class shall not be instantiated, shall not be used as a type and shall contain only static members.

If C.D were not considered a static member, this wording would not allow it to be declared in the static class C.

§15.3.8 *Static and instance members* says:

> When a static member `M` is referenced in a *member_access* (§12.8.7) of the form `E.M`, `E` shall denote a type that has a member `M`. It is a compile-time error for `E` to denote an instance.

From the viewpoint of this wording too, it is good to specify nested types being static members, so that `this.B b1;` is a compile-time error in A.M().

In §12.8.7.2 *Identical simple names and type names* though, there is the wording "the static members and nested types of `E`", which is as if static members did not include nested types already.  It might be clearer to write just "the static members of `E`" and then add a note pointing to the clause that specifies that nested types are static members.
