### ISSUE TITLE
12.14 The null coalescing operator

### ISSUE THREAD

**Issue by gafter** [dotnet/csharpstandard#178]
12.14 (was 13.14) was revised per https://github.com/ECMA-TC49-TG2/spec/issues/593#issuecomment-216352460 to permit `null` on the left-hand-side

> A null coalescing expression of the form `a ?? b` requires a to be the null literal (§7.4.5.7), or to be of a nullable value type or reference type. If `a` is non-null, the result of `a ?? b` is `a`; otherwise, the result is `b`. The operation evaluates `b` only if `a` is null.

However, compilers also accept code such as

``` c#
var p = (null) ?? ""
```

Note that the left-hand-side here isn't a null literal. It is a parenthesized expression containing a null literal.

I suspect this issue occurs elsewhere where "null literal" is called out in the specification as a special case (e.g. 11.2.6 Null literal conversions).

**Comment by Nigel-Ecma** [comment]
I think is likely does fall below the bar; there are probably other odd bits in the Standard caused by the passing of the null type and we could spend a lot of time rooting them all out when in reality the intended semantics are clear – yes its a wart we'd prefer not to have but we live with it.

But as this one was raised can we fix it easily? In 2016 Jon reported (https://github.com/ECMA-TC49-TG2/spec/issues/593):

> We believe that the `null` literal is the *only* expression without a type which is permitted here

but now we find it isn't, at least one compiler allows `(null)` and there could be other expressions accepted...

Consider the 3rd para and start of the bullets:

> The type of the expression `a ?? b` depends on which implicit conversions are available on the operands. In order of preference, the type of `a ?? b` is `A₀`, `A`, or `B`, where `A` is the type of `a` (provided that `a` has a type), `B` is the type of `b`(provided that `b` has a type), and `A₀` is the underlying type of `A` if `A` is a nullable value type, or `A` otherwise. Specifically, `a ?? b` is processed as follows:
>
> -   If `A` exists and is not a nullable value type or a reference type, a compile-time error occurs.
> -   If `b` is a dynamic expression, the result type is `dynamic`. At run-time, `a` is first evaluated. If `a` is not `null`, `a` is converted to `dynamic`, and this becomes the result. Otherwise, `b` is evaluated, and this becomes the result.

The first bullet covers the requirement that if `a` has a type it must be a nullable value or reference type. So we've no need to say that in the 1st paragraph.

The second bullet allows for `a` to be evaluated and tested for not being `null` without requiring `a` to have a type. Assuming that is legal then this bullet should handle `null`, `(null)`, ..., `((((null))))` and any other way to get a typeless result with a null value.

The bullets continue:

> -   Otherwise, if `A` exists and is a nullable value type and an implicit conversion exists from `b` to `A₀`, the result type is `A₀`. At run-time, `a` is first evaluated. If `a` is not `null`, `a` is unwrapped to type `A₀`, and this becomes the result. Otherwise, `b` is evaluated and converted to type `A₀`, and this becomes the result.
> -   Otherwise, if `A` exists and an implicit conversion exists from `b` to `A`, the result type is `A`. At run-time, a is first evaluated. If a is not null, a becomes the result. Otherwise, `b` is evaluated and converted to type `A`, and this becomes the result.
> -   Otherwise, if `A` exists and is a nullable value type, `b` has a type `B` and an implicit conversion exists from `A₀` to `B`, the result type is `B`. At run-time, `a` is first evaluated. If `a` is not `null`, `a` is unwrapped to type `A₀` and converted to type `B`, and this becomes the result. Otherwise, `b` is evaluated and becomes the result.

While all required `a` to have a type so we can skip those, leaving us with:

> -   Otherwise, if `b` has a type `B` and an implicit conversion exists from `a` to `B`, the result type is `B`. At run-time, `a` is first evaluated. If `a` is not `null`, `a` is converted to type `B`, and this becomes the result. Otherwise, `b` is evaluated and becomes the result.

This final bullet gets to deal with `null` and all its parenthesised siblings (and any other way to get an untyped null value, if such exist) – from any such expressions an implicit conversion exists to any `B` which is a nullable value or reference type.

 From the above we see that from the 3rd para onwards the requirements on the value and type of `a` are all covered, so these not be covered in the 1st para at all, which we can reduce to:

> The result of a null coalescing expression of the form `a ?? b` is `a` if `a` is non-null; otherwise, the result is `b`. The operation evaluates `b` only if `a` is `null`.

Which resolves the *raised* issue.

---

However...

As I read the last bullet while typing this I had a thought, hopefully a wayward one. Consider:

    int? i = null;
    int j = i ?? 42;

By the third bullet `j` has the value `42`. Now consider a little hand substitution to get:

    int j = null ?? 42;

Bullets 1-5 do not apply, bullet 6 requires an implicit conversion from `null` to `int`, which leaves us at the final para and a compile-time error...

This seems to violate the principle of minimum surprise.

Is this worth noting?

> *[The above fragments tested on dotnetfiddle.net as I'm not a box with C# as I type. All three compilers available there produce `42` and a compile-time error respecitvely, they also all accept `((((null))))`.]*

**Comment by jskeet** [comment]
Suggestion from @gafter: the bottom part of Nigel's comment, around the surprise, may be worth noting as a suggested language change in the csharplang repo, but not in the standard.
