### ISSUE TITLE
13.2 End points and reachability (throw, empty, and block statements)

### ISSUE THREAD

**Issue by gafter** [dotnet/csharpstandard#179]
13.2 End points and reachability says

> A warning is reported if the compiler determines that a statement is unreachable. It is specifically not an error for a statement to be unreachable.

However, C# compilers have never warned about unreachable statements that are
- A throw statement `throw` ...
- A block statement `{` ...
- An empty statement `;`

It would be nice to adjust the specification to match.

**Comment by Nigel-Ecma** [comment]
> On 9/04/2019, at 2:28 am, Neal Gafter <notifications@github.com> wrote:
> 
> this would enshrine into the Standard the behaviour of certain IDEs
> 
> It enshrines in the standard the behavior of every IDE that uses an existing compiler. The purpose of having a standard is to enshrine industry practice.
> 

Well yes and no…

In general while its good that a Standard stems from actual practice surely a Standard offers something more than just “what the last compiler (bugs and all) does” e.g. stability, certainty, reliability etc. What is the point of a Standard if its just the latest compiler’s documentation? When deciding what goes into a Standard you need to distinguish between quirks of an implementation, which you might find you want to change in the next compiler, and intentional semantics you want to nail down. Of course this often isn’t a simple black/white determination, so you get some mugs ;-) to sit on a committee and figure out what should be standardised and what should be left as an artefact of implementation.

Moving to the specific we have a Standard which did grow out of the documentation of the industry practice, and now we have a current compiler which varies from the Standard. Was the documentation or Standard originally wrong? If it is in the Standard we hope it was examined and seen to be good, or did it slip through? Was it correct and the behaviour has now intentionally changed? Is it a case of a mistake in the compiler but we have to enshrine it now for backward compatibility? Etc. Inquiring minds should surely want to know. I’m not saying the change shouldn’t be made, I’m saying I wasn’t persuaded it should be, which is not the same thing.

We should be mindful of the, probably apocryphal, story that the quirks in Pascal are due to Wirth documenting the behaviour of the compiler he had his students write…

I must say when Apple announced that every version of Swift would probably be breaking, and many certainly have, I wasn’t overly convinced with that approach for a language (then I saw the quirks in the first public version and was glad they were not set in!), but one can sometimes see the advantages of the approach as it avoids issues like this. However it has meant that Swift is more a family of languages, or just one which has grown up from infancy, through an “interesting" adolescence, and might only just be approaching a more stable adulthood ;-)

**Comment by Nigel-Ecma** [comment]
Did we ever discuss this at a meeting (@jskeet last comment) the "meeting: discuss" flag is still on it.

This is largely an issue of philosophy. @gafter says in his last comment "We treat new warnings as being nearly as bad of a breaking change..." – that's certainly not everybody's approach. I regularly use a, non-Microsoft, compiler where I expect each release to introduce new warnings and even errors – and occasionally addressing these can be a drag but generally they're good/helpful and result in improvements. Given C# is firmly in the MS-philosophy camp I think the Standard should/does go that way. Reading it back now I think it was a fun exchange with Neal but provided suitable wording I think we go the way he suggests.

**Comment by jskeet** [comment]
We did discuss it, yes. I *believe* we basically agreed with the original premise of the issue, and decided it would be good to adjust the standard accordingly.

**Comment by Nigel-Ecma** [comment]
Over to @gafter for a PR maybe and remove the *meeting: discuss*?

**Comment by jskeet** [comment]
@Nigel-Ecma: I added "meeting: discuss" to all issues that I assigned, in the hope and expectation that each would have something to discuss :)
