### ISSUE TITLE
12.7.3 Missing spec rule (error for instance method of enclosing class called in nested class)

### ISSUE THREAD

**Issue by gafter** [dotnet/csharpstandard#187]
I cannot find the C# spec rule that makes this an error. Where would I find it?

``` c#
class C1
{
    void M() { }
    class C2
    {
        void Entry()
        {
            M(); // error: object reference required for M
        }
    }
}
```

The closest thing I find is is in 12.7.3 Simple names…

•	Otherwise, the result is the same as a member access (Member access) of the form T.I or T.I<A1,...,Ak>. In this case, it is a binding-time error for the simple_name to refer to an instance member

However, it is a bit misleading. M doesn’t “refer to an instance member”. It refers to a method group. The method group might contain both instance and static methods.

When I look at the section on binding an invocation, I don’t see what error is supposed to be given for this case.

**Comment by jskeet** [comment]
Assigned to myself for investigation before the next meeting.

**Comment by jskeet** [comment]
Okay - I think Neal's analysis is correct, both in terms of the part of [12.7.3.1](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#12731-general) which performs the lookup, and the problem with the final sentence.

I *believe* the fix is straightforward though: remove "In this case, it is a binding-time error for the simple_name to refer to an instance member." That's already covered by member access via `T.I`, including correctly handling method groups, so we don't need to attempt to restate the "not an instance member" restriction.

I'll create a PR for this.
