### ISSUE TITLE
14.5.4, "Using static directives": Example needed

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#199]
At the very end of this subclause we have the following:

> A *using_static_directive* only imports members and types declared directly in the given type, not members and types declared in base classes.
>
> TODO: Example
>
> Ambiguities between multiple *using_namespace_directives* and *using_static_directives* are discussed in [§14.5.3](namespaces.md#1453-using-namespace-directives).

We need someone to provide the example or to argue against doing so.

**Comment by BillWagner** [comment]
Per Jon's comment that mentioned @MadsTorgersen 

The rule in question:

> "A *using_static_directive* only imports members and types declared directly in the given type, not members and types declared in base classes." 

I suspect the reason for this rule is that without it, any `using static` would import the static methods declared in `System.Object`: `Equals(Object, Object)` and `ReferenceEquals(Object, Object)`. With any deeper hierarchy, that would be confusing.

**Comment by BillWagner** [comment]
Discussed in June 30th meeting: That decision is to encourage developers to use the canonical names of types being importing in a `using static` rather than rely on the effects of inheritance.

A downside is that it means moving a `static` member to a base class should be interpreted as a breaking change, because the `using static` directives would be incorrect.

**Comment by BillWagner** [comment]
Added in https://github.com/dotnet/csharpstandard/pull/9/commits/c5ce4490b7ff0837402ec1bf8b4aaa7601500c31
