### ISSUE TITLE
Spec incorrectly requires an enum base be a keyword

### ISSUE THREAD

**Issue by gafter** [dotnet/csharpstandard#277]
In C# 6 we relaxed the syntax of an enum base type to be a type syntax, but require that it bind to one of a specified set of types. So `System.Int32` is permitted. But the spec has not been updated; it still requires one of a set of keywords for the base.

**Comment by MadsTorgersen** [comment]
I believe this is no longer a problem. [19.2 Enum declarations](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/enums.md#192-enum-declarations) allows for a `struct_type` in this position. The prose here and elsewhere directly and indirectly lists the integral types by means of the language keywords, but [9.3.5 Simple types](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/types.md#935-simple-types) makes clear that these are aliases for the corresponding types in the `System` namespace.

**Comment by MadsTorgersen** [comment]
Proposal: Do nothing.

**Comment by gafter** [comment]
Agreed.  The grammar for `struct_type` does indeed allow identifiers.

**Comment by Nigel-Ecma** [comment]
The choice of `struct_type` introduces unnecessary mutual left recursion due to the additional options it allows, so using it is not the best solution to the original issue (that only keywords were allowed). However a better solution, if any, will probably come from other work (see "Pushing the grammar through ANTLR" which touches on this case).
