### ISSUE TITLE
[C# 6] #485 lost ** delimiters in §11.7.6.2 Identical simple names and type names

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#541]
In draft-v6, [§11.7.6.2 Identical simple names and type names](https://github.com/dotnet/csharpstandard/blob/dce002fca40c13d8e64c7c6ed47a9819d5611d11/standard/expressions.md#11762-identical-simple-names-and-type-names) contains an example with `public Color Color`.  Below the code sample, there is a paragraph:

> Within the `A` class, those occurrences of the Color identifier that reference the Color type are delimited by `**`, and those that reference the Color field are not.

However, none of the occurrences are delimited by `**`. The delimiters were deleted in <https://github.com/dotnet/csharpstandard/pull/485>.

**Comment by KalleOlaviNiemitalo** [comment]
If you want to keep the code sample as valid C#, then perhaps you could use `@Color` to indicate references to the Color type. Or perhaps that would just mislead readers.

**Comment by jskeet** [comment]
Rex, do you have time to look at this and make a proposal for next week's meeting?

**Comment by RexJaeschke** [comment]
Back in V5, when the spec was maintained in Word format, the 4 instances that were being called out here were highlighted by being underlined. At some point during the conversion to md, this got turned into pairs of "\*" delimiters. Rather than go back to underlining, which requires embedded HTML that the converter would have to understand, I propose that we use chevron delimiters instead, as follows:

> *Example*:
>
> ```csharp
> struct Color
> {
>     public static readonly Color White = new Color(...);
>     public static readonly Color Black = new Color(...);
>     public Color Complement() {...}
> }
>
> class A
> {
>     public «Color» Color;              // Field Color of type Color
>
>     void F()
>     {
>         Color = «Color».Black;         // Refers to Color.Black static member
>         Color = Color.Complement();  // Invokes Complement() on Color fld
>     }
>
>     static void G()
>     {
>         «Color» c = «Color».White;       // Refers to Color.White static member
>     }
> }
> ```
>
> For expository purposes only, within the `A` class, those occurrences of the `Color` identifier that reference the `Color` type are delimited by `«...»`, and those that reference the `Color` field are not.
>
> *end example*

Note that, ordinarily, we use such delimiters to call out grammar rule names inside of code blocks, but as we explain the usage here, I think it's OK. Besides, we know that these delimiters are handled correctly by the Word converter, as they are simply "just another pair of Unicode characters," and they render correctly in GitHub.

**Comment by jskeet** [comment]
That sounds like an excellent compromise to me.

**Comment by KalleOlaviNiemitalo** [comment]
PR was merged to draft-v6. Can this be closed now?
