### ISSUE TITLE
Verify ref safety rules

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#806]
See https://github.com/dotnet/csharpstandard/pull/795/files#r1218623949

We believe we've managed to capture all the original rules correctly. @gafter made this [gist](https://gist.github.com/gafter/d6068f35deb2a558b08b478f9dba1b1f) which translates the speclet terms to those used in the standard.

Changes can be found in #795 

The edits made incorporating those rules are as follows:

1. Re-order local and parameter rules.
2. Change title of "method invocation" to "function invocation" because the same rules would apply to local function declarations.
3. "Rvalue" changes to "Value" for consistency with the standard's existing terms.
4. "Span constructor" and "default" rules move to structs.md, in the section of "safe context" for `ref struct` types. 

I did a quick scan, and none of the rules were removed, or had other semantic edits.

**Comment by BillWagner** [comment]
Ping @jskeet 

I captured this discussion so I could resolve those conversations and merge the PR.

**Comment by jskeet** [comment]
Thanks - I'll try get to this tomorrow or Friday.

**Comment by jskeet** [comment]
Okay, actually trying to read through this today.  I'll keep notes here. I hadn't looked at the gist before - I expected a set of "things to check" rather than a separate draft spec, but I'll do what I can.

- 12.21.3: "It is a compile time error if the ref-safe-context" should be followed by a link; it's in code font.
- Gist: "We associate with each expression at compile-time the concept of what scope that expression is permitted to escape to"safe-context"" - in 16.4.12.1, this is " each expression whose type is a ref struct" rather than each expression. I think that's okay.
- 16.4.12.7 refers to "current-method"; should that be function-member?
- 16.4.12 general: I think it would be useful to define the three contexts in bold rather than in plain text
- The gist only has two safe-contexts: method and caller; the standard has 3 (declaration-block, function-member, and caller-context) - do we actually need all three?
- Checking the different contexts:
  - Parameters: fine
  - Locals: fine
  - Field references: fine
  - Operators: ref-safe-context looks okay; safe-context needs more work. (We talk about `?:` and `= ref`, but nothing else.)
  - Method invocation:
    - ref-safe-context: "The context of all argument expressions (including the receiver)" should probably refer to the safe-context of all argument expressions
    - safe-context: "calling-method" should be caller-context (I suspect)
  - Property invocations: fine for safe-context as the section is "Method and property invocation" (although that should probably be reflected in the first sentence too); ref-safe-context refers to "Function invocation" without further clarification
  - stackalloc: safe-context should be named function-member, not current-method
  - constructor invocations: look fine; could be elided into "function invocation" for ref-safe-context
  - default expression: this is in 16.4.12.1 rather than a separate rule
 - Language constraints:
   - First three constraints are in 9.7.2.8
   - Type argument constraint is present in 16.2.3, but tuple type isn't
   - Field constraint is in 16.2.3
   - Array element constraint is in 16.2.3
   - Boxing constraint is in 16.2.3, but the bullet ends with a colon
   - Interface constraint is in 16.2.3
   - Instance method in Object/ValueType is in 16.2.3
   - Method group conversion is in 16.2.3
   - ref-reassignment is in 9.7.2.8, but declared with `ref` on the LHS (incorrectly, I think)
   - return ref is in 9.2.7.8
   - Assignment `e1 = e2` is in 16.4.12.1 
   - Method invocation with out/ref argument with ref struct is in 16.4.12.1
   - Local function / anonymous function is in 16.2.3
   - The gist has an open issue "We need some rule that permits us to produce an error when needing to spill a stack value of a ref struct type at an await expression"

The rest of the document is explanations; I haven't checked whether they're present or not.

I'll create a new PR with fixes for the simple bits of the above.

**Comment by jskeet** [comment]
While creating the PR, here are things I'm *not* tackling:

- Operators: ref-safe-context looks okay; safe-context needs more work. (We talk about ?: and = ref, but nothing else.)
- The open issue: "We need some rule that permits us to produce an error when needing to spill a stack value of a ref struct type at an await expression"

Other notes:

- 9.7.2.5 Unsure about my examples of property invocations - do we need to separate get/set?
- 9.7.2.7 Probably simplest *not* to elide this into method/property

**Comment by jskeet** [comment]
For the open issue bit: the standard is tighter than the compiler. 16.2.3 states that ref struct can't be used in async methods at all.

**Comment by jskeet** [comment]
It looks like we're actually okay for safe-context for operators. So #816 should close this.
