### ISSUE TITLE
C# 7.x §6.5.1 quibble: `getCharPositionInLine() == 0` is made informative by a note, which is itself informative

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#851]
**Describe the bug**

In the C# 7.x draft, §6.5.1 (Pre-processing directives / General), there is first a grammar rule that is normative:

```antlr
// Only recognised at the beginning of a line
fragment PP_Start
    // See note below.
    : { getCharPositionInLine() == 0 }? PP_Whitespace? '#' PP_Whitespace?
    ;
```

and then a note that makes the `getCharPositionInLine() == 0` predicate informative:

>> *Note*:
>>
>> - The pre-processor grammar defines a single lexical token `PP_Directive` used for all pre-processing directives. The semantics of each of the pre-processing directives are defined in this language specification but not how to implement them.
>> - The `PP_Start` fragment must only be recognised at the start of a line, the `getCharPositionInLine() == 0` ANTLR lexical predicate above suggests one way in which this may be achieved and is informative *only*, an implementation may use a different strategy.
>>
>> *end note*

However, notes are informative.  Can a note change the meaning of text that would otherwise be normative?

**Example**

None.

**Expected behavior**

Have normative text state that the `getCharPositionInLine() == 0` predicate is informative.

**Additional context**

None.

**Comment by Nigel-Ecma** [comment]
This is blurring the lines a bit on the strict boundaries between normative and informative text, it was intentional ;-) However we need to acknowledge that blurring those boundaries is sometimes helpful. Here the grammar refers directly to the Note, and that in turn makes it clear the predicate is informative; combined these both avoid confusion between the normative and informative, and provide a useful hint to the grammar implementer as to how such semantic rules in ANTLR can be leveraged without a lot of added verbiage – which is of course a subjective judgement!

@jskeet – In the absence of any objections arising I suggest you close this with an appropriate tag indicating we know the boundaries are being bent but no action is required at this time.

Disclaimer: I authored this little bit of boundary bending.

**Comment by jskeet** [comment]
Closing as "wontfix" - we absolutely see where you're coming from @KalleOlaviNiemitalo, but can't think of a genuinely better approach; having the "it's informative" bit in normative text would look odd - the meaning is already clear, really.

**Comment by KalleOlaviNiemitalo** [comment]
In the Common Lisp standard §1.4.3 (Sections Not Formally Part Of This Standard), there is a suggestion that examples and notes could be removed "in order to produce a document of smaller size."  Which I guess could reduce the cost of printing the standard.

Are ECMA standards designed to be trimmed in that manner?

**Comment by RexJaeschke** [comment]
In a word, "NO!" BTW, from 1984-1999, I served on the C standard's committee, and there was a push to be more formal re notation and to remove prose (which can potentially be incomplete/ambiguous), including notes and examples. Fortunately (from my pov), that got no traction. On all std's committees I've worked on since, people have requested more such info, not less.
