### ISSUE TITLE
Missing tables in C.4 (and a typo)

### ISSUE THREAD

**Issue by Nigel-Ecma** [dotnet/csharpstandard#987]
C.4 contains “FIXME: Replace with first format strings table” and “FIXME: Replace with second format strings table”, oops!

These tables did exist and IIRC there was an issue with the Word translator? Anyway they didn’t make it into the final version.

There is also a small typo, `IFormatable` rather than `IFormattable`, which can be fixed alongside putting the tables back.

**Comment by RexJaeschke** [comment]
Thanks @Nigel-Ecma. I have restored the tables, exactly as they existed in V6. After some dialog with Ecma management, I've sent along to them a revised draft of V7 with the deleted placeholders and inserted tables marked using pseudo-tracked changes, which will be turned into ordinary text *before* publication..

I also fixed the typo, but only in the Word version. That still needs to be fixed in the md. As such, I'll leave this issue open until that fix has been made.
